# Generated by Django 4.2.18 on 2025-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_to_sql', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionmodel',
            name='thread_id',
            field=models.CharField(max_length=255),
        ),
    ]
